import {test,expect,type Page} from "@playwright/test";
import {readFileSync,mkdirSync} from "node:fs";
const account=JSON.parse(readFileSync(".local/auth/e2e.json","utf8")) as {password:string;dispatcher:string;supervisor:string;branch:string};
async function checkTemplateTimeInput(page: Page) {
 await page.goto("/admin/planning");
 await page.getByRole("button", { name: "แม่แบบประจำ", exact: true }).click();
 await page.getByRole("button", { name: "เพิ่มแม่แบบ", exact: true }).click();
 const departure = page.locator('input[name="departureMinute"]');
 await departure.fill("0830"); await departure.press("Tab");
 await expect(departure).toHaveValue("08:30");
 await departure.locator("..").getByRole("button", { name: "เปิดตัวเลือกเวลา" }).click();
 const popup = page.getByRole("dialog", { name: "เลือกเวลา", exact: true });
 await popup.getByRole("button", { name: "เพิ่มชั่วโมง", exact: true }).click();
 await popup.getByRole("button", { name: "ใช้เวลา 09:30", exact: true }).click();
 await expect(departure).toHaveValue("09:30");
 expect(await departure.evaluate((input: HTMLInputElement) => new FormData(input.form!).get("departureMinute"))).toBe("09:30");
 await expect(page.getByRole("button", { name: "บันทึกแม่แบบ", exact: true })).toBeVisible();
}
async function login(page:Page,email:string){await page.goto("/login");await page.getByLabel("อีเมล").fill(email);await page.getByLabel("รหัสผ่าน").fill(account.password);await page.getByRole("button",{name:"เข้าสู่ระบบ",exact:true}).click();await expect(page).toHaveURL(email === account.branch ? /\/(?:\?.*)?$/ : /\/admin$/);}
test("T01/T02/T08/T12/T21 and D225: Thai route/template generation, copy/edit/reduce, preview rejection, publish, responsive history, day navigation and multi-day tools",async({page})=>{
 test.setTimeout(120_000);
 await login(page,account.dispatcher);await checkTemplateTimeInput(page);await page.getByRole("button",{name:"กลับรายการแม่แบบ",exact:true}).click();await page.getByRole("button",{name:"ออกโดยไม่บันทึก",exact:true}).click();await expect(page.getByRole("heading",{name:"แผนเดินรถรายวัน",exact:true})).toBeVisible();await page.goto("/admin");await page.getByRole("link",{name:/แผนเดินรถรายวัน/}).click();await expect(page.getByRole("heading",{name:"ความครบถ้วนทุกสาขา"})).toBeVisible();
 await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.getByText("ยังไม่มีเที่ยวในวันนี้",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"เส้นทาง",exact:true}).click();await page.getByRole("button",{name:"เพิ่มเส้นทาง",exact:true}).click();await page.getByLabel("รหัสเส้นทาง",{exact:true}).fill("UI-SYNTHETIC");await page.getByLabel("ชื่อเส้นทาง",{exact:true}).fill("เส้นทางทดสอบหน้าจอ (สังเคราะห์)");
 for(let n=0;n<3;n++){if(n)await page.getByRole("button",{name:"เพิ่มจุดส่ง",exact:true}).click();await page.getByRole("combobox",{name:`จุดส่งที่ ${n+1}`,exact:true}).selectOption(`synthetic-branch-${["a","b","c"][n]}`);}
 await page.getByLabel("เหตุผล",{exact:true}).fill("สร้างเส้นทางทดสอบสังเคราะห์");await page.getByRole("button",{name:"บันทึกเส้นทาง",exact:true}).click();await expect(page.getByRole("status")).toContainText("บันทึกสำเร็จ");
 await page.getByRole("button",{name:"แม่แบบประจำ",exact:true}).click();await page.getByRole("button",{name:"เพิ่มแม่แบบ",exact:true}).click();await page.getByLabel("รหัสแม่แบบ",{exact:true}).fill("UI-TEMPLATE");const option=page.getByRole("combobox",{name:"ฉบับเส้นทาง",exact:true}).locator("option").filter({hasText:"UI-SYNTHETIC"});await page.getByRole("combobox",{name:"ฉบับเส้นทาง",exact:true}).selectOption(await option.getAttribute("value")??"");await page.getByRole("combobox",{name:"รถ",exact:true}).selectOption("synthetic-vehicle-1");
 await page.getByLabel("เริ่มขึ้นของ",{exact:true}).fill("07:00");await page.getByLabel("ออกรถ",{exact:true}).fill("08:00");await page.getByLabel("ถึงปลายทาง",{exact:true}).fill("10:00");await page.locator('input[name="occupancyStartMinute"]').fill("07:00");await page.locator('input[name="occupancyEndMinute"]').fill("10:00");for(const box of await page.getByRole("checkbox",{name:/^(หมู|ไก่)$/}).all())await box.check();await page.getByLabel("เหตุผล",{exact:true}).fill("แม่แบบสังเคราะห์สำหรับทดสอบ");await page.getByRole("button",{name:"บันทึกแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("บันทึกสำเร็จ");
 await page.getByRole("button",{name:"แผนรายวัน",exact:true}).click();await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("สร้างเที่ยวสังเคราะห์จากแม่แบบ");await page.getByRole("button",{name:"สร้างเที่ยวจากแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("สร้างเที่ยวเพิ่ม 2 เที่ยว");await page.getByRole("button",{name:"สร้างเที่ยวจากแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("สร้างเที่ยวเพิ่ม 0 เที่ยว");
 const unknown=page.locator(".trip-card").filter({hasText:"ยังไม่ระบุรถ"});await unknown.getByRole("button",{name:"นำเที่ยวออกจากฉบับร่าง",exact:true}).click();await page.getByRole("button",{name:"ยืนยันดำเนินการ",exact:true}).click();await expect(page.locator(".trip-card")).toHaveCount(1);

 mkdirSync("docs/evidence/planning-ux",{recursive:true});
 await page.reload();await expect(page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true})).toHaveValue("01/05/2570");await expect(page.locator(".trip-card")).toHaveCount(1);
 const details=page.locator(".trip-card").first().getByRole("button",{name:"ดูรายละเอียด",exact:true});await details.click();await expect(page.getByRole("dialog")).toContainText("PORK");await page.screenshot({path:"docs/evidence/planning-ux/trip-detail-1440.png"});await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).toHaveCount(0);await expect(details).toBeFocused();
 await page.locator(".trip-card").first().getByRole("button",{name:"แก้ไข",exact:true}).click();await expect(page).toHaveURL(/planning\/edit\?/);await page.reload();await expect(page.getByRole("heading",{name:"แก้ไขเที่ยวรถ",exact:true})).toBeVisible();
 await page.locator(".editor-advanced summary").click();await page.locator('input[name="bufferMinutes"]').fill("1");
 await page.goBack();await expect(page.getByRole("dialog",{name:"มีข้อมูลที่ยังไม่บันทึก"})).toBeVisible();await page.getByRole("button",{name:"แก้ไขต่อ",exact:true}).click();await expect(page.locator('input[name="bufferMinutes"]')).toHaveValue("1");
 await page.getByRole("button",{name:/กลับแผน/}).click();await page.getByRole("button",{name:"ออกโดยไม่บันทึก",exact:true}).click();await expect(page.locator(".trip-card")).toHaveCount(1);
 await page.locator(".trip-card").first().getByRole("button",{name:"แก้ไข",exact:true}).click();await page.locator(".editor-advanced summary").click();await page.locator('input[name="bufferMinutes"]').fill("2");
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/evidence/planning-ux/trip-editor-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:1440,height:1000});
 await page.route("**/api/planning",async route=>{if(route.request().method()==="POST")await route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({message:"ทดสอบการบันทึกไม่สำเร็จ"})});else await route.continue();});
 await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".planning-edit-page").getByRole("alert")).toContainText("ทดสอบการบันทึกไม่สำเร็จ");await expect(page.locator('input[name="bufferMinutes"]')).toHaveValue("2");
 await page.unroute("**/api/planning");await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".trip-card")).toHaveCount(1);await expect(page.getByRole("status")).toContainText("บันทึกเที่ยวแล้ว");
 for(const round of [2,3]){await page.locator(".trip-card").first().getByRole("button",{name:"คัดลอก",exact:true}).click();await page.getByRole("combobox",{name:"รอบส่งสาขา",exact:true}).selectOption(String(round));await page.getByRole("combobox",{name:"รถ",exact:true}).selectOption(`synthetic-vehicle-${round}`);await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".trip-table")).toBeVisible();}
 await expect(page.locator(".cell-complete")).toHaveCount(18);await expect(page.getByRole("button",{name:"เผยแพร่แผน",exact:true})).toHaveCount(1);/* D221: the planner prepares and publishes */
 // Merge a copied draft, persist cancellation history, then remove the never-published member.
 const beforeMerge=await (await page.request.get("/api/planning?date=2027-05-01")).json();
 await page.locator(".trip-card").first().getByRole("button",{name:"คัดลอก",exact:true}).click();
 await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".trip-card")).toHaveCount(4);await page.locator(".planner-details > summary").click();
 const afterCopy=await (await page.request.get("/api/planning?date=2027-05-01")).json();
 const sourceId=afterCopy.trips.find((t:{tripId:string})=>!beforeMerge.trips.some((old:{tripId:string})=>old.tripId===t.tripId)).tripId;
 await page.getByRole("combobox",{name:"เที่ยวต้นทาง",exact:true}).selectOption(sourceId!);
 await page.getByRole("combobox",{name:"เที่ยวปลายทาง",exact:true}).selectOption(beforeMerge.trips.find((t:{code:string})=>t.code.startsWith("UI-TEMPLATE-")).tripId);/* generated trips are named after their template and date */
 await page.getByRole("button",{name:"รวมเที่ยวในฉบับร่าง",exact:true}).click();await page.getByRole("button",{name:"ยืนยันดำเนินการ",exact:true}).click();

 await expect(page.locator(".trip-cancelled")).toHaveCount(1);
 await page.locator(".trip-cancelled").getByRole("button",{name:"นำเที่ยวออกจากฉบับร่าง",exact:true}).click();await page.getByRole("button",{name:"ยืนยันดำเนินการ",exact:true}).click();

 await expect(page.locator(".trip-card")).toHaveCount(3);
 // Save one deliberately missing category, then exercise the actual supervisor rejection.
 await page.locator(".trip-card").last().getByRole("button",{name:"แก้ไข",exact:true}).click();await page.getByRole("checkbox",{name:"ไก่",exact:true}).last().uncheck();await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".trip-table")).toBeVisible();await expect(page.locator(".cell-missing")).toHaveCount(1);
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.supervisor);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-missing")).toHaveCount(1);await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("ทดสอบการปฏิเสธช่องส่งไม่ครบ");await page.getByRole("checkbox",{name:/ตรวจสอบความครบถ้วน/}).check();await expect(page.getByRole("button",{name:"เผยแพร่แผน",exact:true})).toBeDisabled();
 const missingPlan=await (await page.request.get("/api/planning?date=2027-05-01")).json();
 const rejected=await page.request.post("/api/planning",{headers:{Origin:"http://127.0.0.1:3011","Idempotency-Key":crypto.randomUUID()},data:{action:"publish",input:{revisionId:missingPlan.selectedRevisionId,expectedVersion:missingPlan.version,reason:"ทดสอบปฏิเสธช่องที่ขาด",reassignments:[]}}});expect(rejected.ok()).toBe(false);expect((await rejected.json()).code).toBe("COVERAGE_MISSING");
 await page.locator(".cell-missing button").click();await expect(page.getByRole("dialog")).toContainText("เลือกเที่ยวส่งสาขารอบนี้");await page.getByRole("button",{name:"กลับไปตรวจสอบ",exact:true}).click();mkdirSync("docs/evidence/phase-4",{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/evidence/phase-4/rejected-coverage.png",fullPage:true});
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.dispatcher);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-missing")).toHaveCount(1);await page.locator(".trip-card").last().getByRole("button",{name:"แก้ไข",exact:true}).click();await page.getByRole("checkbox",{name:"ไก่",exact:true}).last().check();await page.getByRole("button",{name:"บันทึกเที่ยวและตรวจแผน",exact:true}).click();await expect(page.locator(".trip-table")).toBeVisible();await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("เติมหมวดสินค้าสังเคราะห์ให้ครบ");await expect(page.locator(".cell-complete")).toHaveCount(18);
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.supervisor);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-complete")).toHaveCount(18);await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("อนุมัติแผนสังเคราะห์ครบถ้วน");await page.getByRole("checkbox",{name:/ตรวจสอบความครบถ้วน/}).check();await page.getByRole("button",{name:"เผยแพร่แผน",exact:true}).click();await expect(page.getByRole("dialog",{name:"ยืนยันเผยแพร่แผน"})).toBeVisible();await page.getByRole("button",{name:"ยืนยันดำเนินการ",exact:true}).click();await expect(page.getByRole("status")).toContainText("เผยแพร่แผนสำเร็จ");
 mkdirSync("docs/evidence/phase-4",{recursive:true});for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect(page.getByRole("heading",{name:"แผนเดินรถรายวัน",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/evidence/phase-4/planner-${width}.png`,fullPage:true});}await page.getByRole("button",{name:"ประวัติการเปลี่ยนแปลง",exact:true}).click();await expect(page.getByText("เหตุผล: อนุมัติแผนสังเคราะห์ครบถ้วน",{exact:true})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/evidence/phase-4/history-390.png",fullPage:true});
 // D225: day bar, two-week strip and multi-day tools, in the same signed-in session (sign-ins are rate limited).
 mkdirSync("docs/evidence/planning-redesign",{recursive:true});await page.setViewportSize({width:1440,height:1000});await page.getByRole("button",{name:"แผนรายวัน",exact:true}).click();
 await page.screenshot({path:"docs/evidence/planning-redesign/published-day-1440.png",fullPage:true});
 await page.getByRole("button",{name:"วันนี้",exact:true}).click();
 const strip=page.getByRole("navigation",{name:/ภาพรวมแผนรายวัน/});await expect(strip.locator(".week-day")).toHaveCount(14);
 await expect(page.locator(".missing-plans")).toContainText("ยังไม่มีแผนที่เผยแพร่ 7 วัน");
 await expect(page.locator(".day-title .plan-chip").filter({hasText:/^วันนี้$/})).toBeVisible();await expect(page.locator(".day-title")).toContainText("ยังไม่มีแผน");const title=page.locator(".day-title h2"),todayTitle=await title.textContent();
 await page.getByRole("button",{name:"วันถัดไป",exact:true}).click();await expect(title).not.toHaveText(todayTitle!);
 await page.getByRole("button",{name:"วันก่อนหน้า",exact:true}).click();await expect(title).toHaveText(todayTitle!);
 await page.locator(".range-tools > summary").click();await page.getByRole("button",{name:"สร้างร่างจากแม่แบบ",exact:true}).click();
 await expect(page.locator(".range-results tbody tr")).toHaveCount(7);await expect(page.locator(".range-results tbody tr").first()).toContainText("สร้างร่าง");
 await expect(strip.locator(".week-day.plan-draft")).toHaveCount(7);await expect(page.locator(".trip-card").first()).toBeVisible();
 // The generated drafts lack rounds 2 and 3, so publishing several days at once skips every one of them and says why.
 await page.getByRole("checkbox",{name:/ดูภาพรวมรายวันด้านบนแล้ว/}).check();await page.getByRole("button",{name:"เผยแพร่วันที่พร้อม",exact:true}).click();
 await expect(page.locator(".range-results tbody tr")).toHaveCount(7);await expect(page.locator(".range-results")).toContainText("ยังขาด");await expect(page.getByRole("status")).toContainText("เผยแพร่สำเร็จ 0 วัน จาก 7 วัน");await expect(strip.locator(".week-day.plan-draft")).toHaveCount(7);
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/evidence/planning-redesign/draft-day-${width}.png`,fullPage:true});}
 // Read-response fixture reproduces the owner's noncanonical category code without mutating real master data.
 await page.route("**/api/planning?date=*",async route=>{const response=await route.fetch();const data=await response.json();data.categories=data.categories.map((c:{code:string})=>c.code==="PORK"?{...c,code:"PORK ทดสอบ"}:c);await route.fulfill({response,json:data});});
 await page.reload();await expect(page.locator(".coverage-guidance")).toContainText("PORK");await expect(page.getByRole("link",{name:"เปิดรายการหมวดสินค้า"})).toHaveAttribute("href","/admin/product-categories");await page.screenshot({path:"docs/evidence/planning-ux/category-guidance-390.png",fullPage:true});await page.unroute("**/api/planning?date=*");
});
test("T13: branch scope cannot read planning API or page; unauthenticated write denied",async({page})=>{
 expect((await page.request.get("/api/planning?date=2027-05-01")).status()).toBe(401);await login(page,account.branch);expect((await page.request.get("/api/planning?date=2027-05-01")).status()).toBe(403);expect((await page.request.post("/api/planning",{headers:{Origin:"http://127.0.0.1:3011","Idempotency-Key":"wrong-role"},data:{action:"draft",input:{serviceDate:"2027-06-01",expectedVersion:0,trips:[],reason:"พนักงานสาขาไม่มีสิทธิ์แก้แผน"}}})).status()).toBe(403);await page.goto("/admin/planning");await expect(page.getByRole("heading",{name:"ไม่มีสิทธิ์เข้าถึงแผนเดินรถ"})).toBeVisible();
});
