import {test,expect,type Page} from "@playwright/test";
import {readFileSync,mkdirSync} from "node:fs";
const account=JSON.parse(readFileSync(".local/auth/e2e.json","utf8")) as {password:string;dispatcher:string;supervisor:string;branch:string};
async function login(page:Page,email:string){await page.goto("/login");await page.getByLabel("อีเมล").fill(email);await page.getByLabel("รหัสผ่าน").fill(account.password);await page.getByRole("button",{name:"เข้าสู่ระบบ",exact:true}).click();await expect(page).toHaveURL(email === account.branch ? /\/(?:\?.*)?$/ : /\/admin$/);}
test("T01/T02/T08/T12/T21: Thai route/template generation, copy/edit/reduce, preview rejection, publish and responsive history",async({page})=>{
 await login(page,account.dispatcher);await page.getByRole("link",{name:/แผนเดินรถรายวัน/}).click();await expect(page.getByRole("heading",{name:"ความครบถ้วนทุกสาขา"})).toBeVisible();
 await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.getByText("ยังไม่มีเที่ยวในวันนี้",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"เส้นทาง",exact:true}).click();await page.getByRole("button",{name:"เพิ่มเส้นทาง",exact:true}).click();await page.getByLabel("รหัสเส้นทาง",{exact:true}).fill("UI-SYNTHETIC");await page.getByLabel("ชื่อเส้นทาง",{exact:true}).fill("เส้นทางทดสอบหน้าจอ (สังเคราะห์)");
 for(let n=0;n<3;n++){if(n)await page.getByRole("button",{name:"เพิ่มจุดส่ง",exact:true}).click();await page.getByRole("combobox",{name:`จุดส่งที่ ${n+1}`,exact:true}).selectOption(`synthetic-branch-${["a","b","c"][n]}`);}
 await page.getByLabel("เหตุผล",{exact:true}).fill("สร้างเส้นทางทดสอบสังเคราะห์");await page.getByRole("button",{name:"บันทึกเส้นทาง",exact:true}).click();await expect(page.getByRole("status")).toContainText("บันทึกสำเร็จ");
 await page.getByRole("button",{name:"แม่แบบประจำ",exact:true}).click();await page.getByRole("button",{name:"เพิ่มแม่แบบ",exact:true}).click();await page.getByLabel("รหัสแม่แบบ",{exact:true}).fill("UI-TEMPLATE");const option=page.getByRole("combobox",{name:"ฉบับเส้นทาง",exact:true}).locator("option").filter({hasText:"UI-SYNTHETIC"});await page.getByRole("combobox",{name:"ฉบับเส้นทาง",exact:true}).selectOption(await option.getAttribute("value")??"");await page.getByRole("combobox",{name:"รถ",exact:true}).selectOption("synthetic-vehicle-1");
 await page.getByLabel("เริ่มขึ้นของ",{exact:true}).fill("07:00");await page.getByLabel("ออกรถ",{exact:true}).fill("08:00");await page.getByLabel("ถึงปลายทาง",{exact:true}).fill("10:00");await page.locator('input[name="occupancyStartMinute"]').fill("07:00");await page.locator('input[name="occupancyEndMinute"]').fill("10:00");for(const box of await page.getByRole("checkbox",{name:/^(หมู|ไก่)$/}).all())await box.check();await page.getByLabel("เหตุผล",{exact:true}).fill("แม่แบบสังเคราะห์สำหรับทดสอบ");await page.getByRole("button",{name:"บันทึกแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("บันทึกสำเร็จ");
 await page.getByRole("button",{name:"แผนรายวัน",exact:true}).click();await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("สร้างเที่ยวสังเคราะห์จากแม่แบบ");await page.getByRole("button",{name:"สร้างเที่ยวจากแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("สร้างเที่ยวเพิ่ม 2 เที่ยว");await page.getByRole("button",{name:"สร้างเที่ยวจากแม่แบบ",exact:true}).click();await expect(page.getByRole("status")).toContainText("สร้างเที่ยวเพิ่ม 0 เที่ยว");
 const unknown=page.locator(".trip-card").filter({hasText:"ยังไม่ระบุรถ"});await unknown.getByRole("button",{name:"ลบเที่ยวฉบับร่าง",exact:true}).click();await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();await expect(page.locator(".trip-card")).toHaveCount(1);
 for(const round of [2,3]){await page.locator(".trip-card").first().getByRole("button",{name:"คัดลอก",exact:true}).click();await page.locator(".trip-card").last().getByRole("button",{name:"แก้ไข / ลดจุดส่ง",exact:true}).click();await page.getByRole("combobox",{name:"รอบส่งสาขา",exact:true}).selectOption(String(round));await page.getByRole("combobox",{name:"รถ",exact:true}).selectOption(`synthetic-vehicle-${round}`);await page.getByRole("button",{name:"ใช้การแก้ไขเที่ยวนี้",exact:true}).click();}
 await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();await expect(page.locator(".cell-complete")).toHaveCount(18);await expect(page.getByRole("button",{name:"เผยแพร่แผน",exact:true})).toHaveCount(1);/* D221: the planner prepares and publishes */
 // Merge a copied draft, persist cancellation history, then remove the never-published member.
 const beforeMerge=await (await page.request.get("/api/planning?date=2027-05-01")).json();
 await page.locator(".trip-card").first().getByRole("button",{name:"คัดลอก",exact:true}).click();
 const sourceOptions=page.getByRole("combobox",{name:"เที่ยวต้นทาง",exact:true}).locator("option");
 const sourceId=await sourceOptions.last().getAttribute("value");
 await page.getByRole("combobox",{name:"เที่ยวต้นทาง",exact:true}).selectOption(sourceId!);
 await page.getByRole("combobox",{name:"เที่ยวปลายทาง",exact:true}).selectOption(beforeMerge.trips[0].tripId);
 await page.getByRole("button",{name:"รวมเที่ยวในฉบับร่าง",exact:true}).click();
 await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();
 await expect(page.locator(".trip-cancelled")).toHaveCount(1);
 await page.locator(".trip-cancelled").getByRole("button",{name:"ลบเที่ยวฉบับร่าง",exact:true}).click();
 await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();
 await expect(page.locator(".trip-card")).toHaveCount(3);
 // Save one deliberately missing category, then exercise the actual supervisor rejection.
 await page.locator(".trip-card").last().getByRole("button",{name:"แก้ไข / ลดจุดส่ง",exact:true}).click();await page.getByRole("checkbox",{name:"ไก่",exact:true}).last().uncheck();await page.getByRole("button",{name:"ใช้การแก้ไขเที่ยวนี้",exact:true}).click();await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();await expect(page.locator(".cell-missing")).toHaveCount(1);
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.supervisor);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-missing")).toHaveCount(1);await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("ทดสอบการปฏิเสธช่องส่งไม่ครบ");await page.getByRole("checkbox",{name:/ตรวจสอบความครบถ้วน/}).check();await page.getByRole("button",{name:"เผยแพร่แผน",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"ยังส่งหมูและไก่ไม่ครบ"})).toBeVisible();mkdirSync("docs/evidence/phase-4",{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/evidence/phase-4/rejected-coverage.png",fullPage:true});
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.dispatcher);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-missing")).toHaveCount(1);await page.locator(".trip-card").last().getByRole("button",{name:"แก้ไข / ลดจุดส่ง",exact:true}).click();await page.getByRole("checkbox",{name:"ไก่",exact:true}).last().check();await page.getByRole("button",{name:"ใช้การแก้ไขเที่ยวนี้",exact:true}).click();await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("เติมหมวดสินค้าสังเคราะห์ให้ครบ");await page.getByRole("button",{name:"บันทึกฉบับร่างและตรวจสอบ",exact:true}).click();await expect(page.locator(".cell-complete")).toHaveCount(18);
 await page.getByRole("button",{name:/^บัญชี /}).click();await page.getByRole("button",{name:"ออกจากระบบ",exact:true}).click();await login(page,account.supervisor);await page.goto("/admin/planning");await page.getByLabel("วันที่ให้บริการ (พ.ศ.)",{exact:true}).fill("01/05/2570");await page.getByRole("button",{name:"เปิดวันที่",exact:true}).click();await expect(page.locator(".cell-complete")).toHaveCount(18);await page.getByLabel("เหตุผลการเปลี่ยนแปลงหรือเผยแพร่").fill("อนุมัติแผนสังเคราะห์ครบถ้วน");await page.getByRole("checkbox",{name:/ตรวจสอบความครบถ้วน/}).check();await page.getByRole("button",{name:"เผยแพร่แผน",exact:true}).click();await expect(page.getByRole("status")).toContainText("เผยแพร่แผนสำเร็จ");
 mkdirSync("docs/evidence/phase-4",{recursive:true});for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await expect(page.getByRole("heading",{name:"แผนเดินรถรายวัน",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`docs/evidence/phase-4/planner-${width}.png`,fullPage:true});}await page.getByRole("button",{name:"ประวัติการเปลี่ยนแปลง",exact:true}).click();await expect(page.getByText("เหตุผล: อนุมัติแผนสังเคราะห์ครบถ้วน",{exact:true})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/evidence/phase-4/history-390.png",fullPage:true});
});
test("T13: branch scope cannot read planning API or page; unauthenticated write denied",async({page})=>{
 expect((await page.request.get("/api/planning?date=2027-05-01")).status()).toBe(401);await login(page,account.branch);expect((await page.request.get("/api/planning?date=2027-05-01")).status()).toBe(403);expect((await page.request.post("/api/planning",{headers:{Origin:"http://127.0.0.1:3011","Idempotency-Key":"wrong-role"},data:{action:"draft",input:{serviceDate:"2027-06-01",expectedVersion:0,trips:[],reason:"พนักงานสาขาไม่มีสิทธิ์แก้แผน"}}})).status()).toBe(403);await page.goto("/admin/planning");await expect(page.getByRole("heading",{name:"ไม่มีสิทธิ์เข้าถึงแผนเดินรถ"})).toBeVisible();
});
