import "dotenv/config";
import assert from "node:assert/strict";
import {after,before,test} from "node:test";
import {createDatabase} from "../../src/server/persistence/database";
import {testDatabaseConfiguration} from "../../src/server/config/environment";
import {saveRoute,saveTemplate,generateTrips,draftTrips,type TemplateInput} from "../../src/server/services/planning-catalog";
import {saveDraft,publishPlan} from "../../src/server/services/plans";
import {planningData} from "../../src/server/services/planning-read";
import {DomainError} from "../../src/server/domain/errors";
import {installRoles} from "../../src/server/auth/permissions";
import {seedMasters,synthetic,completeDraft} from "../fixtures/synthetic";
const db=createDatabase(testDatabaseConfiguration(process.env)),other=createDatabase(testDatabaseConfiguration(process.env)),actor=synthetic.actorId;
const rejected=(code:string)=>(e:unknown)=>e instanceof DomainError&&e.code===code;
before(async()=>{await seedMasters(db);await installRoles(db);});after(async()=>{await db.$disconnect();await other.$disconnect();});
test("T11/T12: route/template ordered revisions, FK lifecycle, optimistic concurrent editors and immutable history",async()=>{
 const input={id:"p4-route",code:"P4-ROUTE",expectedVersion:0,active:true,effectiveFrom:"2027-01-01",effectiveTo:null,name:"เส้นทางสังเคราะห์ทดสอบ",branchIds:[...synthetic.branchIds],reason:"สร้างเส้นทางสังเคราะห์"};
 const r=await saveRoute(db,actor,"p4-route-create",input);
 assert.deepEqual((await db.routeStop.findMany({where:{routeRevisionId:r.revisionId},orderBy:{sequence:"asc"}})).map(s=>s.branchId),synthetic.branchIds);
 const results=await Promise.allSettled([saveRoute(db,actor,"p4-route-race-a",{...input,expectedVersion:1,name:"ฉบับสังเคราะห์ ก"}),saveRoute(other,actor,"p4-route-race-b",{...input,expectedVersion:1,name:"ฉบับสังเคราะห์ ข"})]);
 assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.ok(results.some(r=>r.status==="rejected"&&rejected("VERSION_CONFLICT")(r.reason)));
 assert.equal((await db.routeRevision.findUniqueOrThrow({where:{id:r.revisionId}})).name,input.name);
 await assert.rejects(db.route.delete({where:{id:r.id}}));
 const stops=await db.routeStop.findMany({where:{routeRevisionId:r.revisionId}});
 const t:TemplateInput={id:"p4-template",code:"P4-TEMPLATE",expectedVersion:0,active:true,effectiveFrom:"2027-01-01",effectiveTo:null,reason:"แม่แบบสังเคราะห์",routeRevisionId:r.revisionId,kind:"BRANCH_DELIVERY",roundNo:1,vehicleId:synthetic.vehicleIds[0],driverId:null,loadingMinute:420,departureMinute:null,arrivalMinute:600,arrivalDayOffset:0,occupancyStartMinute:420,occupancyEndMinute:600,bufferMinutes:0,notes:"ข้อมูลสังเคราะห์ ไม่ใช่ตารางจริง",weekdays:[1,2,3,4,5,6,7],categories:stops.map(s=>({routeStopId:s.id,categoryIds:[...synthetic.categoryIds]}))};
 const v1=await saveTemplate(db,actor,"p4-template-create",t);
 const generated=await generateTrips(db,actor,"p4-generate-1",{serviceDate:"2027-01-04",expectedVersion:0,reason:"สร้างเที่ยวสังเคราะห์"});
 const count=await db.trip.count({where:{planId:generated.planId}});assert.ok(count>=1);
 const replay=await generateTrips(db,actor,"p4-generate-1",{serviceDate:"2027-01-04",expectedVersion:0,reason:"สร้างเที่ยวสังเคราะห์"});assert.deepEqual(generated,replay);
 const repeat=await generateTrips(db,actor,"p4-generate-2",{serviceDate:"2027-01-04",expectedVersion:generated.version,reason:"สร้างซ้ำด้วยรหัสใหม่"});assert.equal(repeat.generated,0);assert.equal(repeat.version,generated.version);
 await saveTemplate(db,actor,"p4-template-edit",{...t,expectedVersion:1,departureMinute:480,notes:"แก้เฉพาะแม่แบบใหม่"});
 const oldTrip=await db.tripRevision.findFirstOrThrow({where:{planRevisionId:generated.revisionId,templateRevisionId:v1.revisionId}});assert.equal(oldTrip.departureAt,null);assert.equal(oldTrip.notes,t.notes);
 await assert.rejects(db.templateRevision.update({where:{id:v1.revisionId},data:{departureMinute:480}}));
 const info=await planningData(db,actor,"2027-01-04");assert.ok(info.issues.some(s=>s.includes("ยังไม่ระบุ")));assert.equal(await db.trip.count({where:{planId:generated.planId}}),count);
});
test("T01/T02/T03/T07/T12: saved preview, missing coverage, capacity rejection, stale writers and atomic replacement",async()=>{
 const input=completeDraft("2027-02-01","p4-full");input.reason="แผนสังเคราะห์ครบถ้วน";
 const draft=await saveDraft(db,actor,"p4-full-draft",input);const published=await publishPlan(db,actor,"p4-full-publish",{revisionId:draft.revisionId,expectedVersion:draft.version,reason:"ทดสอบครบสิบแปดช่อง"});
 const info=await planningData(db,actor,input.serviceDate);assert.equal(info.missing.length,0);assert.equal(info.eligible.length*6,18);
 const edits=await Promise.allSettled([saveDraft(db,actor,"p4-edit-a",{...input,expectedVersion:published.version}),saveDraft(other,actor,"p4-edit-b",{...input,expectedVersion:published.version})]);assert.equal(edits.filter(r=>r.status==="fulfilled").length,1);assert.ok(edits.some(r=>r.status==="rejected"&&rejected("VERSION_CONFLICT")(r.reason)));
 const latest=await planningData(db,actor,input.serviceDate);const trips=structuredClone(input.trips);trips[2].stops[2].categoryIds=[synthetic.categoryIds[0]];
 const incomplete=await saveDraft(db,actor,"p4-incomplete",{...input,trips,expectedVersion:latest.version});await assert.rejects(publishPlan(db,actor,"p4-incomplete-publish",{revisionId:incomplete.revisionId,expectedVersion:incomplete.version}),rejected("COVERAGE_MISSING"));
 assert.equal((await db.dailyPlan.findUniqueOrThrow({where:{id:draft.planId}})).publishedRevisionId,published.revisionId);
 const oversized=structuredClone(input.trips);oversized[0].plannedLoad="1001";oversized[0].loadUnit="KG";
 const over=await saveDraft(db,actor,"p4-capacity",{...input,trips:oversized,expectedVersion:incomplete.version});await assert.rejects(publishPlan(db,actor,"p4-capacity-publish",{revisionId:over.revisionId,expectedVersion:over.version}),rejected("CAPACITY_EXCEEDED"));
 const omitted=input.trips.slice(1);await assert.rejects(saveDraft(db,actor,"p4-delete-published",{...input,trips:omitted,expectedVersion:over.version}),rejected("TRIP_DELETE_FORBIDDEN"));
});
test("T08: merge/cancel with explicit atomic reassignment, rollback and label revocation preserves snapshots/packages",async()=>{
 const i=completeDraft("2027-03-01","p4-move");const extra=structuredClone(i.trips[0]);extra.tripId="p4-extra";extra.code="P4-EXTRA";extra.vehicleId=synthetic.vehicleIds[1];extra.occupancyStart="2027-02-28T22:00:00.000Z";extra.loadingAt=extra.occupancyStart;extra.departureAt="2027-02-28T23:00:00.000Z";extra.arrivalAt="2027-03-01T00:00:00.000Z";extra.occupancyEnd=extra.arrivalAt;i.trips.push(extra);
 const d=await saveDraft(db,actor,"p4-move-draft",i),p=await publishPlan(db,actor,"p4-move-publish",{revisionId:d.revisionId,expectedVersion:d.version});
 const tr=await db.tripRevision.findUniqueOrThrow({where:{planRevisionId_tripId:{planRevisionId:d.revisionId,tripId:extra.tripId}}}),stop=await db.tripStop.findFirstOrThrow({where:{tripRevisionId:tr.id,branchId:synthetic.branchIds[0]}});
 await db.user.create({data:{id:"p4-requester",subject:"synthetic:p4-requester",displayName:"ผู้ฝากสังเคราะห์ P4"}});
 const c=await db.consignment.create({data:{id:"p4-consignment",code:"P4-SYNTHETIC-CONSIGNMENT",requesterId:"p4-requester",departmentId:"synthetic-department",sourceWarehouseId:"synthetic-warehouse",destinationBranchId:synthetic.branchIds[0]}});
 const pkg=await db.consignmentPackage.create({data:{consignmentId:c.id,sequence:1,total:1}});
 const snap=await db.addressSnapshot.create({data:{createdById:actor,branchId:synthetic.branchIds[0],payload:{synthetic:true,address:"ที่อยู่สังเคราะห์เดิม"}}});
 const a=await db.consignmentAssignment.create({data:{consignmentId:c.id,tripId:tr.tripId,tripRevisionId:tr.id,stopId:stop.id,senderSnapshotId:snap.id,recipientSnapshotId:snap.id,transportSnapshot:{synthetic:true},reason:"สังเคราะห์",approvedById:actor,approvedAt:new Date()}});
 await db.consignment.update({where:{id:c.id},data:{status:"ASSIGNED",currentAssignmentId:a.id}});const label=await db.labelVersion.create({data:{assignmentId:a.id,number:1,lookupToken:"p4-synthetic-label",payload:{synthetic:true}}});await db.labelPackage.create({data:{labelVersionId:label.id,packageId:pkg.id}});
 i.trips[3].cancelled=true;let next=await saveDraft(db,actor,"p4-merge-draft",{...i,expectedVersion:p.version});
 await assert.rejects(publishPlan(db,actor,"p4-missing-move",{revisionId:next.revisionId,expectedVersion:next.version}),rejected("REASSIGNMENT_REQUIRED"));
 const move={consignmentId:c.id,expectedVersion:1,tripId:i.trips[0].tripId,stopSequence:1};
 await assert.rejects(publishPlan(db,actor,"p4-wrong-stop",{revisionId:next.revisionId,expectedVersion:next.version,reason:"ย้ายสังเคราะห์",reassignments:[{...move,stopSequence:2}]}),rejected("INVALID_ASSIGNMENT"));
 assert.equal((await db.labelVersion.findUniqueOrThrow({where:{id:label.id}})).revokedAt,null);assert.equal((await db.consignment.findUniqueOrThrow({where:{id:c.id}})).currentAssignmentId,a.id);
 const oversized=structuredClone(i);oversized.trips[0].plannedLoad="2000";oversized.trips[0].loadUnit="KG";const bad=await saveDraft(db,actor,"p4-late-rollback-draft",{...oversized,expectedVersion:next.version});
 await assert.rejects(publishPlan(db,actor,"p4-late-rollback",{revisionId:bad.revisionId,expectedVersion:bad.version,reason:"ทดสอบย้อนกลับหลังย้ายพัสดุ",reassignments:[move]}),rejected("CAPACITY_EXCEEDED"));
 assert.equal((await db.labelVersion.findUniqueOrThrow({where:{id:label.id}})).revokedAt,null);assert.equal((await db.consignment.findUniqueOrThrow({where:{id:c.id}})).currentAssignmentId,a.id);assert.equal(await db.consignmentEvent.count({where:{consignmentId:c.id,kind:"ASSIGNED"}}),0);
 next=await saveDraft(db,actor,"p4-after-rollback-draft",{...i,expectedVersion:bad.version});
 const result=await publishPlan(db,actor,"p4-move-success",{revisionId:next.revisionId,expectedVersion:next.version,reason:"รวมเที่ยวสังเคราะห์และย้ายพัสดุ",reassignments:[move]});
 const current=await db.consignment.findUniqueOrThrow({where:{id:c.id},include:{currentAssignment:true}});assert.equal(current.version,2);assert.equal(current.currentAssignment?.previousAssignmentId,a.id);assert.equal(current.currentAssignment?.recipientSnapshotId,snap.id);assert.ok((await db.labelVersion.findUniqueOrThrow({where:{id:label.id}})).revokedAt);assert.equal(await db.consignmentPackage.count({where:{id:pkg.id}}),1);assert.equal(await db.consignmentEvent.count({where:{consignmentId:c.id,kind:"ASSIGNED"}}),1);
 assert.deepEqual(await publishPlan(db,actor,"p4-move-success",{revisionId:next.revisionId,expectedVersion:next.version,reason:"รวมเที่ยวสังเคราะห์และย้ายพัสดุ",reassignments:[move]}),result);
 await db.consignment.update({where:{id:c.id},data:{status:"LOADED"}});const locked=await saveDraft(db,actor,"p4-loaded-draft",{...i,expectedVersion:result.version});await assert.rejects(publishPlan(db,actor,"p4-loaded-publish",{revisionId:locked.revisionId,expectedVersion:locked.version,reason:"ห้ามย้ายที่ขึ้นรถแล้ว",reassignments:[{...move,expectedVersion:2}]}),rejected("CONSIGNMENT_IN_MOTION"));
 assert.equal((await db.dailyPlan.findUniqueOrThrow({where:{id:d.planId}})).publishedRevisionId,result.revisionId);
});
test("T21/T13: concurrent semantic generation, draft deletion and globally scoped planning reads",async()=>{
 const attempts=await Promise.allSettled([generateTrips(db,actor,"p4-gen-race-a",{serviceDate:"2027-04-01",expectedVersion:0,reason:"สร้างพร้อมกันสังเคราะห์"}),generateTrips(other,actor,"p4-gen-race-b",{serviceDate:"2027-04-01",expectedVersion:0,reason:"สร้างพร้อมกันสังเคราะห์"})]);assert.equal(attempts.filter(r=>r.status==="fulfilled").length,1);
 const info=await planningData(db,actor,"2027-04-01");const count=info.trips.length;assert.ok(count>0);const saved=await saveDraft(db,actor,"p4-delete-draft",{serviceDate:"2027-04-01",expectedVersion:info.version,trips:[],reason:"ลบเที่ยวที่ยังไม่เคยเผยแพร่"});assert.equal((await db.$transaction(tx=>draftTrips(tx,saved.revisionId))).length,0);assert.equal(await db.trip.count({where:{planId:saved.planId}}),count);
 const again=await generateTrips(db,actor,"p4-gen-after-delete",{serviceDate:"2027-04-01",expectedVersion:saved.version,reason:"ห้ามสร้างซ้ำหลังนำออก"});assert.equal(again.generated,0);
 const u=await db.user.create({data:{subject:"p4-scoped-dispatcher",displayName:"ผู้จัดรถขอบเขตสาขาสังเคราะห์"}}),role=await db.role.findUniqueOrThrow({where:{code:"DISPATCHER"}});await db.userRole.create({data:{userId:u.id,roleId:role.id}});await db.userScope.create({data:{userId:u.id,kind:"BRANCH",branchId:synthetic.branchIds[0]}});
 await assert.rejects(planningData(db,u.id,"2027-04-01"),rejected("FORBIDDEN"));await assert.rejects(generateTrips(db,u.id,"p4-no-scope",{serviceDate:"2027-04-02",expectedVersion:0,reason:"ถูกปฏิเสธข้ามขอบเขต"}),rejected("FORBIDDEN"));
});
test("T12: historical stop names survive master renames; duplicate dated codes are rejected",async()=>{
 const plan=await db.dailyPlan.findUniqueOrThrow({where:{serviceDate:new Date("2027-02-01")}});
 const before=await db.$transaction(tx=>draftTrips(tx,plan.publishedRevisionId!));const branch=await db.branch.findUniqueOrThrow({where:{id:synthetic.branchIds[0]}});
 try{await db.branch.update({where:{id:branch.id},data:{name:"ชื่อปัจจุบันสังเคราะห์ที่เปลี่ยนแล้ว"}});const history=await planningData(db,actor,"2027-02-01",plan.publishedRevisionId);assert.equal(history.trips[0].stops[0].nameSnapshot,before[0].stops[0].nameSnapshot);assert.notEqual(history.trips[0].stops[0].nameSnapshot,history.branches.find(b=>b.id===branch.id)?.name);}finally{await db.branch.update({where:{id:branch.id},data:{name:branch.name}});}
 const input=completeDraft("2027-07-01","p4-duplicate");input.trips[0].code=before[0].code;await assert.rejects(saveDraft(db,actor,"p4-duplicate-code",input),rejected("DUPLICATE_TRIP"));
});
