"use client";
import {useCallback,useEffect,useState} from "react";
import type {PlanningData} from "@/server/services/planning-read";
import type {DraftTrip} from "@/server/services/plans";
import {TripEditor} from "./planning-trip-editor";
import {DateInput} from "./date-time-inputs";
import {RouteEditor,TemplateEditor} from "./planning-catalog-editor";
import {beDate,isoDate,kindLabels,localInstant,statusLabels} from "./planning-fields";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const actionLabels:Record<string,string>={PLAN_DRAFT_CREATED:"สร้างฉบับร่าง",PLAN_PUBLISHED:"เผยแพร่แผน",ROUTE_REVISED:"แก้ไขเส้นทาง",TEMPLATE_REVISED:"แก้ไขแม่แบบ",CONSIGNMENT_REASSIGNED:"ย้ายพัสดุ"};
export function PlanningWorkspace(){
 const [data,setData]=useState<PlanningData|null>(null),[date,setDate]=useState(today),[dateText,setDateText]=useState(()=>beDate(today())),[tab,setTab]=useState("plan"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[trips,setTrips]=useState<DraftTrip[]>([]),[dirty,setDirty]=useState(false),[editor,setEditor]=useState<DraftTrip|null>(null),[catalog,setCatalog]=useState<{kind:string;id?:string}|null>(null),[reason,setReason]=useState(""),[round,setRound]=useState("all"),[mergeSource,setMergeSource]=useState(""),[mergeTarget,setMergeTarget]=useState(""),[moves,setMoves]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false);
 const load=useCallback(async(day:string,revision?:string)=>{
  const r=await fetch(`/api/planning?date=${encodeURIComponent(day)}${revision?`&revision=${encodeURIComponent(revision)}`:""}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.message??"โหลดแผนไม่สำเร็จ");setData(d);setTrips(d.trips);setDirty(false);setEditor(null);setMoves({});setConfirmed(false);
 },[]);
 useEffect(()=>{let alive=true;fetch(`/api/planning?date=${today()}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);if(alive){setData(d);setTrips(d.trips);}}).catch(()=>{if(alive){setFailed(true);setMessage("โหลดแผนไม่สำเร็จ กรุณาลองเปิดวันที่อีกครั้ง");}});return()=>{alive=false;};},[]);
 const save=async(action:string,input:unknown)=>{setBusy(true);setFailed(false);setMessage("");try{const r=await fetch("/api/planning",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({action,input})}),result=await r.json();if(!r.ok)throw Error(result.message??"บันทึกไม่สำเร็จ");await load(date,result.revisionId&&["draft","publish","generate"].includes(action)?result.revisionId:undefined);setMessage(action==="publish"?"เผยแพร่แผนสำเร็จ พร้อมเก็บประวัติฉบับก่อนหน้า":action==="generate"?`สร้างเที่ยวเพิ่ม ${result.generated} เที่ยว โดยรักษาเที่ยวเดิม`:"บันทึกสำเร็จ ตรวจสอบฉบับล่าสุดได้ด้านล่าง");return true;}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:"เชื่อมต่อไม่ได้ กรุณาโหลดข้อมูลเพื่อตรวจสอบผลก่อนลองอีกครั้ง");return false;}finally{setBusy(false);}};
 const change=(next:DraftTrip[])=>{setTrips(next);setDirty(true);setConfirmed(false);};
 const openDate=async()=>{setBusy(true);try{const d=isoDate(dateText);await load(d);setDate(d);setMessage("");setFailed(false);}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:"โหลดไม่สำเร็จ");}finally{setBusy(false);}};
 const newTrip=()=>{const id=crypto.randomUUID();setEditor({tripId:id,code:`T-${id.slice(0,12)}`,kind:"BRANCH_DELIVERY",roundNo:1,cancelled:false,vehicleId:null,loadingAt:null,departureAt:null,arrivalAt:null,occupancyStart:null,occupancyEnd:null,bufferMinutes:0,stops:[]});};
 const merge=()=>{const source=trips.find(t=>t.tripId===mergeSource),target=trips.find(t=>t.tripId===mergeTarget);if(!source||!target||source===target||source.cancelled||target.cancelled||source.kind!==target.kind||source.roundNo!==target.roundNo){setFailed(true);setMessage("เลือกเที่ยวที่ยังไม่ยกเลิก ประเภทและรอบเดียวกันสองเที่ยวเพื่อรวม");return;}if(source.plannedLoad||target.plannedLoad){setFailed(true);setMessage("กรุณาตรวจปริมาณรวมและปรับเที่ยวปลายทางด้วยการแก้ไข จากนั้นยกเลิกเที่ยวต้นทาง เพื่อไม่ให้รวมปริมาณต่างหน่วยโดยไม่ตั้งใจ");return;}const stops=target.stops.map(s=>({...s,categoryIds:[...s.categoryIds]}));for(const s of source.stops){const found=stops.find(t=>t.branchId===s.branchId);if(found)found.categoryIds=[...new Set([...found.categoryIds,...s.categoryIds])];else stops.push(s);}change(trips.map(t=>t===source?{...t,cancelled:true}:t===target?{...t,stops}:t));setMessage("รวมจุดส่งเข้าเที่ยวปลายทางและยกเลิกเที่ยวต้นทางในหน้าจอแล้ว กรุณาตรวจเวลาและบันทึกฉบับร่าง");};
 const canWrite=data?.permissions.includes("plan.write"),canPublish=data?.permissions.includes("plan.publish"),selected=data?.revisions.find(r=>r.id===data.selectedRevisionId);
 return <><div className="planner-title"><span className="eyebrow">จัดการเดินรถ</span><h1>แผนเดินรถรายวัน</h1><p className="muted">จัดเส้นทาง ตรวจความครบถ้วน และเผยแพร่แผนที่ตรวจสอบย้อนหลังได้</p></div>
 <div className="planner-tabs" role="navigation" aria-label="เมนูวางแผน">{[["plan","แผนรายวัน"],["routes","เส้นทาง"],["templates","แม่แบบประจำ"],["audit","ประวัติการเปลี่ยนแปลง"]].map(([key,label])=><button key={key} disabled={dirty&&tab!==key} onClick={()=>{setTab(key);setCatalog(null);}} className={tab===key?"selected":""} aria-pressed={tab===key}>{label}</button>)}</div>
 <div className="admin-card planner-toolbar"><label>วันที่ให้บริการ (พ.ศ.)<DateInput value={dateText} onChange={setDateText} aria-label="วันที่ให้บริการ (พ.ศ.)" required/></label><button className="secondary-button" disabled={busy||dirty} onClick={()=>void openDate()}>เปิดวันที่</button><p className="muted">เวลาไทย • เว้นว่างเมื่อยังไม่ทราบ</p></div>
 {message&&<p role={failed?"alert":"status"} className={failed?"form-error admin-card":"admin-card planner-notice"}>{message}</p>}{busy&&<p role="status">กำลังตรวจสอบและบันทึกข้อมูล…</p>}
 {!data?<p className="admin-card">{failed?"ยังไม่สามารถโหลดข้อมูลได้":"กำลังโหลดแผนเดินรถ…"}</p>:<fieldset disabled={busy} className="planner-fieldset">
 {tab==="plan"&&<><div className="planner-metrics"><article><strong>{data.eligible.length}</strong><span>สาขาที่ต้องส่ง</span></article><article><strong>{data.eligible.length*6-data.missing.length} / {data.eligible.length*6}</strong><span>ช่องส่งหมูและไก่ครบแล้ว</span></article><article><strong>{trips.filter(t=>!t.cancelled).length}</strong><span>เที่ยวที่ใช้งานในฉบับนี้</span></article></div>
 <section className="admin-card"><div className="form-grid"><label>ฉบับแผน<select value={data.selectedRevisionId??""} disabled={dirty} onChange={async e=>{try{await load(date,e.target.value);}catch{setMessage("โหลดฉบับแผนไม่สำเร็จ");setFailed(true);}}}><option value="" disabled>ยังไม่มีฉบับแผน</option>{data.revisions.map(r=><option key={r.id} value={r.id}>ฉบับ {r.number} — {statusLabels[r.status]}</option>)}</select></label><label>แสดงรอบ<select value={round} onChange={e=>setRound(e.target.value)}><option value="all">ทุกรอบ</option>{[1,2,3].map(n=><option key={n} value={n}>รอบ {n}</option>)}<option value="other">รับเข้าคลังและรถขาย</option></select></label><label>เหตุผลการเปลี่ยนแปลงหรือเผยแพร่<input value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={500} placeholder="ระบุสิ่งที่ปรับและเหตุผล"/></label></div>
 <p className="muted">{data.publishedRevisionId?`ฉบับที่เผยแพร่ใช้งานอยู่: ${data.revisions.find(r=>r.id===data.publishedRevisionId)?.number}`:"วันนี้ยังไม่มีแผนที่เผยแพร่"} • รุ่นข้อมูล {data.version}</p>{dirty&&<p className="form-error" role="status">มีการแก้ไขที่ยังไม่บันทึก ตารางความครบถ้วนด้านล่างเป็นผลของฉบับที่บันทึกครั้งล่าสุด</p>}
 <div className="planner-actions">{canWrite&&<><button onClick={newTrip} className="secondary-button">เพิ่มเที่ยว</button><button onClick={()=>void save("generate",{serviceDate:date,expectedVersion:data.version,reason})} disabled={dirty||reason.trim().length<3}>สร้างเที่ยวจากแม่แบบ</button><button className="primary-button" disabled={reason.trim().length<3} onClick={()=>void save("draft",{serviceDate:date,expectedVersion:data.version,trips,reason})}>บันทึกฉบับร่างและตรวจสอบ</button></>}<button disabled={dirty} onClick={()=>void load(date,data.selectedRevisionId??undefined).catch(()=>{setFailed(true);setMessage("ตรวจสอบไม่สำเร็จ กรุณาลองใหม่");})}>ตรวจสอบความครบถ้วน</button></div></section>
 {canWrite&&editor&&<TripEditor key={editor.tripId} trip={editor} data={data} onClose={()=>setEditor(null)} onSave={t=>{change(trips.some(x=>x.tripId===t.tripId)?trips.map(x=>x.tripId===t.tripId?t:x):[...trips,t]);setEditor(null);}}/>}
 <div className="planner-trip-grid">{trips.filter(t=>round==="all"||(round==="other"?t.kind!=="BRANCH_DELIVERY":t.kind==="BRANCH_DELIVERY"&&String(t.roundNo)===round)).map(t=><article key={t.tripId} className={`admin-card trip-card ${t.cancelled?"trip-cancelled":""}`}><div className="admin-heading"><h2>{t.code}</h2><span className="status-badge">{t.cancelled?"ยกเลิก":`${kindLabels[t.kind]}${t.roundNo?` • รอบ ${t.roundNo}`:""}`}</span></div><p><strong>{data.vehicles.find(v=>v.id===t.vehicleId)?.plateNormalized??"ยังไม่ระบุรถ"}</strong> • {data.drivers.find(d=>d.id===t.driverId)?.name??"ยังไม่ระบุพนักงานขับรถ"}</p><dl className="trip-times"><dt>เริ่มขึ้นของ</dt><dd>{localInstant(t.loadingAt)||"ยังไม่ระบุ"}</dd><dt>ออกรถ</dt><dd>{localInstant(t.departureAt)||"ยังไม่ระบุ"}</dd><dt>ถึงปลายทาง</dt><dd>{localInstant(t.arrivalAt)||"ยังไม่ระบุ"}</dd><dt>ช่วงใช้รถ</dt><dd>{localInstant(t.occupancyStart)||"ยังไม่ระบุ"} ถึง {localInstant(t.occupancyEnd)||"ยังไม่ระบุ"}</dd><dt>เวลาเผื่อ</dt><dd>{t.bufferMinutes} นาที</dd><dt>ความจุรถ</dt><dd>{data.vehicles.find(v=>v.id===t.vehicleId)?.capacity??"ยังไม่ระบุ"} {({KG:"กิโลกรัม",TON:"ตัน",BOX:"กล่อง",PIECE:"ชิ้น",LITER:"ลิตร"} as Record<string,string>)[data.vehicles.find(v=>v.id===t.vehicleId)?.capacityUnit??""]??""}</dd><dt>บรรทุกตามแผน</dt><dd>{t.plannedLoad??"ยังไม่ระบุ"} {({KG:"กิโลกรัม",TON:"ตัน",BOX:"กล่อง",PIECE:"ชิ้น",LITER:"ลิตร"} as Record<string,string>)[t.loadUnit??""]??""}</dd></dl><ol className="trip-stops">{t.stops.map((s,n)=><li key={n}>{s.nameSnapshot??data.branches.find(b=>b.id===s.branchId)?.name??"จุดส่งเดิม"}<span>{s.categoryIds.map(id=>data.categories.find(c=>c.id===id)?.name).join(" / ")||"ยังไม่ระบุหมวดสินค้า"}</span></li>)}</ol>{t.notes&&<p>{t.notes}</p>}{canWrite&&<div className="planner-actions"><button onClick={()=>setEditor(t)}>แก้ไข / ลดจุดส่ง</button><button onClick={()=>{const id=crypto.randomUUID();change([...trips,{...structuredClone(t),tripId:id,code:`T-${id.slice(0,12)}`,cancelled:false}]);}}>คัดลอก</button><button onClick={()=>change(trips.map(x=>x===t?{...x,cancelled:!x.cancelled}:x))}>{t.cancelled?"คืนเที่ยว":"ยกเลิกเที่ยว"}</button><button onClick={()=>change(trips.filter(x=>x!==t))}>ลบเที่ยวฉบับร่าง</button></div>}</article>)}</div>{!trips.length&&<div className="admin-card planner-empty"><h2>ยังไม่มีเที่ยวในวันนี้</h2><p>เพิ่มเที่ยวด้วยตนเอง หรือสร้างจากแม่แบบที่มีผลในวันที่เลือก</p></div>}
 {canWrite&&trips.length>1&&<section className="admin-card"><h2>รวมเที่ยวในรอบเดียวกัน</h2><p className="muted">คงเที่ยวปลายทาง รวมจุดส่งและหมวดสินค้า แล้วเปลี่ยนเที่ยวต้นทางเป็นยกเลิก ตรวจเวลาและพัสดุที่ได้รับผลกระทบก่อนเผยแพร่</p><div className="form-grid"><label>เที่ยวต้นทาง<select value={mergeSource} onChange={e=>setMergeSource(e.target.value)}><option value="">เลือกเที่ยว</option>{trips.filter(t=>!t.cancelled).map(t=><option key={t.tripId} value={t.tripId}>{t.code}</option>)}</select></label><label>เที่ยวปลายทาง<select value={mergeTarget} onChange={e=>setMergeTarget(e.target.value)}><option value="">เลือกเที่ยว</option>{trips.filter(t=>!t.cancelled).map(t=><option key={t.tripId} value={t.tripId}>{t.code}</option>)}</select></label></div><button onClick={merge}>รวมเที่ยวในฉบับร่าง</button></section>}
 <section className="admin-card"><h2>ความครบถ้วนทุกสาขา</h2><p className="muted">ทุกสาขาที่ใช้งานต้องได้รับทั้งหมูและไก่ในทั้ง ๓ รอบ เที่ยวรับเข้าคลัง รถขาย และเที่ยวที่ยกเลิกไม่นับ</p><div className="planner-table-scroll" tabIndex={0} role="region" aria-label="ตารางความครบถ้วน เลื่อนแนวนอนได้"><table className="coverage-table"><thead><tr><th scope="col">สาขา</th>{[1,2,3].flatMap(n=>["หมู","ไก่"].map(c=><th key={`${n}${c}`} scope="col">รอบ {n}<br/>{c}</th>))}</tr></thead><tbody>{data.eligible.map(b=><tr key={b.id}><th scope="row">{b.name}</th>{[1,2,3].flatMap(n=>["PORK","CHICKEN"].map(c=>{const missing=data.missing.some(m=>m.branchId===b.id&&m.roundNo===n&&m.categoryCode===c);return <td key={`${n}${c}`} className={missing?"cell-missing":"cell-complete"}>{missing?"ขาด":"✓ ครบ"}</td>;}))}</tr>)}</tbody></table></div>{!data.eligible.length&&<p>ยังไม่มีสาขาที่มีผลในวันนี้ กรุณาตรวจข้อมูลหลักก่อนเผยแพร่</p>}</section>
 <section className="admin-card"><h2>ผลกระทบและข้อขัดแย้งก่อนเผยแพร่</h2><p>เที่ยวที่เปลี่ยนจากฉบับเผยแพร่: {data.changed.length} เที่ยว • ช่องส่งที่ยังขาด: {data.missing.length} ช่อง • พัสดุที่ต้องจัดเที่ยวใหม่: {data.linked.length} ใบ</p>{data.changed.length>0&&<p className="muted">{data.changed.join(" · ")}</p>}{data.issues.length>0?<ul>{data.issues.map((x,n)=><li key={n}>{x}</li>)}</ul>:<p>ไม่พบปัญหาเบื้องต้นด้านเวลาและการจองรถ ระบบจะตรวจเงื่อนไขทั้งหมดอีกครั้งขณะเผยแพร่</p>}{data.linked.map(c=><div className="stop-editor" key={c.id}><strong>{c.code}</strong><p>{data.branches.find(b=>b.id===c.destinationBranchId)?.name} • {statusLabels[c.status]??"สถานะเดิม"} • รุ่น {c.version}</p><label>เที่ยวและจุดส่งใหม่<select value={moves[c.id]??""} onChange={e=>{setMoves({...moves,[c.id]:e.target.value});setConfirmed(false);}} disabled={!canPublish}><option value="">เลือกปลายทางเพื่อยืนยันการย้าย</option>{trips.filter(t=>!t.cancelled&&t.kind==="BRANCH_DELIVERY").flatMap(t=>t.stops.map((s,n)=>s.branchId===c.destinationBranchId?<option key={`${t.tripId}:${n}`} value={`${t.tripId}:${n+1}`}>{t.code} • รอบ {t.roundNo} • จุด {n+1}</option>:null))}</select></label></div>)}{data.linked.length>0&&<p className="muted">พัสดุที่ขึ้นรถ ออกเดินทาง หรือมีการรับแล้วจะย้ายไม่ได้ การย้ายที่สำเร็จจะรักษาประวัติเดิมและยกเลิกป้ายฉบับเดิม</p>}
 {canPublish&&<><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>ตรวจสอบความครบถ้วน การใช้รถ และผลกระทบต่อพัสดุแล้ว</label><button className="primary-button" disabled={dirty||!confirmed||reason.trim().length<3||selected?.status!=="DRAFT"||data.linked.some(c=>!moves[c.id])} onClick={()=>void save("publish",{revisionId:data.selectedRevisionId,expectedVersion:data.version,reason,reassignments:data.linked.map(c=>{const [tripId,sequence]=moves[c.id].split(":");return {consignmentId:c.id,expectedVersion:c.version,tripId,stopSequence:Number(sequence)};})})}>เผยแพร่แผน</button></>}</section></>}
 {tab==="routes"&&<><div className="admin-heading"><h2>เส้นทางและลำดับจุดส่ง</h2>{data.permissions.includes("route.write")&&<button className="primary-button" onClick={()=>setCatalog({kind:"route"})}>เพิ่มเส้นทาง</button>}</div>{catalog?.kind==="route"&&<RouteEditor key={catalog.id??"new"} data={data} id={catalog.id} save={save} close={()=>setCatalog(null)}/>}<div className="planner-trip-grid">{data.routes.map(r=><article className="admin-card" key={r.id}><h3>{r.code} — {r.routeRevision_routeId[0]?.name}</h3><p>{r.active?"เปิดใช้งาน":"เก็บเข้าคลัง"} • รุ่น {r.version}</p>{data.permissions.includes("route.write")&&<button onClick={()=>setCatalog({kind:"route",id:r.id})}>แก้ไขเส้นทาง</button>}<details><summary>ฉบับย้อนหลัง {r.routeRevision_routeId.length} ฉบับ</summary>{r.routeRevision_routeId.map(v=><div key={v.id}><p>ฉบับ {v.number} • {v.name} • {beDate(v.effectiveFrom)} ถึง {v.effectiveTo?beDate(v.effectiveTo):"ไม่กำหนด"}</p><ol>{v.routeStop_routeRevisionId.map(s=><li key={s.id}>{data.branches.find(b=>b.id===s.branchId)?.name}</li>)}</ol></div>)}</details></article>)}</div>{!data.routes.length&&<p className="admin-card">ยังไม่มีเส้นทาง</p>}</>}
 {tab==="templates"&&<><div className="admin-heading"><h2>แม่แบบเดินรถประจำ</h2>{data.permissions.includes("template.write")&&<button className="primary-button" onClick={()=>setCatalog({kind:"template"})}>เพิ่มแม่แบบ</button>}</div>{catalog?.kind==="template"&&<TemplateEditor key={catalog.id??"new"} data={data} id={catalog.id} save={save} close={()=>setCatalog(null)}/>}<div className="planner-trip-grid">{data.templates.map(t=><article className="admin-card" key={t.id}><h3>{t.code}</h3><p>{t.active?"เปิดใช้งาน":"เก็บเข้าคลัง"} • รุ่น {t.version}</p>{data.permissions.includes("template.write")&&<button onClick={()=>setCatalog({kind:"template",id:t.id})}>แก้ไขแม่แบบ</button>}<details><summary>ฉบับย้อนหลัง {t.templateRevision_templateId.length} ฉบับ</summary>{t.templateRevision_templateId.map(r=><p key={r.id}>ฉบับ {r.number} • {kindLabels[r.kind]} • รอบ {r.roundNo}<br/>{beDate(r.effectiveFrom)} ถึง {r.effectiveTo?beDate(r.effectiveTo):"ไม่กำหนด"}</p>)}</details></article>)}</div>{!data.templates.length&&<p className="admin-card">ยังไม่มีแม่แบบประจำ</p>}</>}
 {tab==="audit"&&<section className="admin-card"><h2>ประวัติฉบับและเหตุผล</h2><p className="muted">แสดงล่าสุดไม่เกิน ๑๐๐ รายการของแผนวันที่เลือก เส้นทาง และแม่แบบ</p>{data.revisions.map(r=><article key={r.id} className="audit-entry"><strong>ฉบับ {r.number} • {statusLabels[r.status]}</strong><p>สร้างโดย {r.createdBy.displayName} • {localInstant(r.createdAt)}</p>{r.publishedAt&&<p>เผยแพร่โดย {r.publishedBy?.displayName} • {localInstant(r.publishedAt)}</p>}</article>)}{data.audit.map(a=><article key={a.id} className="audit-entry"><strong>{actionLabels[a.action]??"ปรับปรุงข้อมูล"}</strong><p>{a.actor.displayName} • {localInstant(a.createdAt)}</p><p>เหตุผล: {a.reason??"ไม่ได้ระบุในรายการเดิม"}</p>{a.before&&typeof a.before==="object"&&!Array.isArray(a.before)&&"version"in a.before&&<p>รุ่นก่อนแก้ไข: {String(a.before.version)}</p>}{a.after&&typeof a.after==="object"&&!Array.isArray(a.after)&&"version"in a.after&&<p>รุ่นหลังแก้ไข: {String(a.after.version)}</p>}</article>)}{!data.audit.length&&<p>ยังไม่มีประวัติการเปลี่ยนแปลง</p>}</section>}
 </fieldset>}</>;
}
