"use client";
import {useState} from "react";
import type {DraftTrip} from "@/server/services/plans";
import type {PlanningData} from "@/server/services/planning-read";
import {field,kindLabels,localInstant,utcInstant} from "./planning-fields";
export function TripEditor({trip,data,onSave,onClose}:{trip:DraftTrip;data:PlanningData;onSave:(trip:DraftTrip)=>void;onClose:()=>void}){
 const [stops,setStops]=useState(trip.stops),[error,setError]=useState("");
 const move=(n:number,delta:number)=>{const copy=[...stops];[copy[n],copy[n+delta]]=[copy[n+delta],copy[n]];setStops(copy);};
 return <form className="admin-card admin-form planner-editor" onSubmit={e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),kind=field(f,"kind") as DraftTrip["kind"];onSave({...trip,code:field(f,"code"),kind,roundNo:kind==="BRANCH_DELIVERY"?Number(f.get("roundNo")):null,vehicleId:field(f,"vehicleId")||null,driverId:field(f,"driverId")||null,loadingAt:utcInstant(field(f,"loadingAt")),departureAt:utcInstant(field(f,"departureAt")),arrivalAt:utcInstant(field(f,"arrivalAt")),occupancyStart:utcInstant(field(f,"occupancyStart")),occupancyEnd:utcInstant(field(f,"occupancyEnd")),bufferMinutes:Number(f.get("bufferMinutes")),notes:field(f,"notes")||null,plannedLoad:field(f,"plannedLoad")||null,loadUnit:field(f,"plannedLoad")?field(f,"loadUnit"):null,stops});}catch(e){setError(e instanceof Error?e.message:"ข้อมูลไม่ถูกต้อง");}}}>
 <div className="admin-heading"><h2>แก้ไขเที่ยวและลำดับจุดส่ง</h2><button type="button" className="secondary-button" onClick={onClose}>ปิด</button></div>
 <p className="muted">เว้นเวลาว่างเมื่อยังไม่ทราบ • วันที่ใช้ พ.ศ. และเวลาไทย ๒๔ ชั่วโมง • การแก้ไขจะอยู่ในหน้าจอจนกดบันทึกฉบับร่าง</p>
 <div className="form-grid"><label>รหัสเที่ยว<input name="code" defaultValue={trip.code} required maxLength={64} readOnly={data.trips.some(t=>t.tripId===trip.tripId)}/></label><label>ประเภทเที่ยว<select name="kind" defaultValue={trip.kind}>{Object.entries(kindLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>รอบส่งสาขา<select name="roundNo" defaultValue={trip.roundNo??1}>{[1,2,3].map(n=><option key={n} value={n}>รอบ {n}</option>)}</select></label>
 <label>รถ<select name="vehicleId" defaultValue={trip.vehicleId??""}><option value="">ยังไม่ระบุ</option>{data.vehicles.filter(v=>v.active||v.id===trip.vehicleId).map(v=><option key={v.id} value={v.id}>{v.plateNormalized} {v.province}{!v.active?" (ไม่พร้อมใช้)":""}</option>)}</select></label><label>พนักงานขับรถ<select name="driverId" defaultValue={trip.driverId??""}><option value="">ยังไม่ระบุ</option>{data.drivers.filter(d=>d.active||d.id===trip.driverId).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 {([['loadingAt','เริ่มขึ้นของ'],['departureAt','ออกรถ'],['arrivalAt','ถึงปลายทาง'],['occupancyStart','เริ่มใช้รถ'],['occupancyEnd','สิ้นสุดใช้รถ']] as const).map(([key,label])=><label key={key}>{label} (วัน/เดือน/ปี พ.ศ. ชั่วโมง:นาที)<input name={key} defaultValue={localInstant(trip[key])} placeholder="วว/ดด/ปปปป ชช:นน"/></label>)}
 <label>เวลาเผื่อหลังใช้รถ (นาที)<input name="bufferMinutes" type="number" min={0} max={1440} defaultValue={trip.bufferMinutes} required/></label><label>ปริมาณบรรทุกตามแผน<input name="plannedLoad" type="number" min="0.001" step="0.001" defaultValue={trip.plannedLoad??""}/></label><label>หน่วยบรรทุก<select name="loadUnit" defaultValue={trip.loadUnit??"KG"}><option value="KG">กิโลกรัม</option><option value="TON">ตัน</option><option value="BOX">กล่อง</option><option value="PIECE">ชิ้น</option><option value="LITER">ลิตร</option></select></label><label>หมายเหตุ<textarea name="notes" defaultValue={trip.notes??""} maxLength={2000}/></label></div>
 <h3>จุดส่งและหมวดสินค้าประจำจุด</h3>{stops.map((s,n)=><fieldset className="stop-editor" key={n}><legend>จุดส่งที่ {n+1}</legend><label>สาขาหรือจุดรับส่ง<select value={s.branchId} onChange={e=>setStops(stops.map((x,k)=>k===n?{...x,branchId:e.target.value,nameSnapshot:undefined}:x))} required><option value="">เลือกจุดส่ง</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.code} — {b.name}{b.archived?" (เก็บเข้าคลัง)":""}</option>)}</select></label><div className="planner-checks">{data.categories.filter(c=>c.active||s.categoryIds.includes(c.id)).map(c=><label key={c.id}><input type="checkbox" checked={s.categoryIds.includes(c.id)} onChange={e=>setStops(stops.map((x,k)=>k===n?{...x,categoryIds:e.target.checked?[...x.categoryIds,c.id]:x.categoryIds.filter(id=>id!==c.id)}:x))}/>{c.name}</label>)}</div><div className="planner-actions"><button type="button" onClick={()=>move(n,-1)} disabled={n===0}>เลื่อนขึ้น</button><button type="button" onClick={()=>move(n,1)} disabled={n===stops.length-1}>เลื่อนลง</button><button type="button" onClick={()=>setStops(stops.filter((_,k)=>k!==n))}>ลดจุดส่งนี้</button></div></fieldset>)}
 <button type="button" className="secondary-button" onClick={()=>setStops([...stops,{branchId:"",categoryIds:[]}])}>เพิ่มจุดส่ง</button>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary-button" type="submit">ใช้การแก้ไขเที่ยวนี้</button></form>;
}
