"use client";
import {ArrowLeft} from "lucide-react";
import {useState} from "react";
import type {PlanningData} from "@/server/services/planning-read";
import {DateField,field,isoDate,kindLabels,minuteText,minuteValue} from "./planning-fields";
import {TimeInput} from "./date-time-inputs";
import { newUuid } from "@/lib/new-uuid";
type Save=(action:string,input:unknown)=>Promise<boolean>;
export function RouteEditor({data,id,save,close}:{data:PlanningData;id?:string;save:Save;close:()=>void}){
 const row=data.routes.find(r=>r.id===id),r=row?.routeRevision_routeId[0];const [stops,setStops]=useState(r?.routeStop_routeRevisionId.map(s=>s.branchId)??[""]),[error,setError]=useState("");
 return <form className="admin-card admin-form" onSubmit={async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);if(await save("route",{id:row?.id??newUuid(),code:field(f,"code"),expectedVersion:row?.version??0,active:f.get("active")==="on",name:field(f,"name"),effectiveFrom:isoDate(field(f,"from")),effectiveTo:field(f,"to")?isoDate(field(f,"to")):null,reason:field(f,"reason"),branchIds:stops}))close();}catch(e){setError(e instanceof Error?e.message:"ข้อมูลไม่ถูกต้อง");}}}>
 <h2>{row?"แก้ไขเส้นทางเป็นฉบับใหม่":"เพิ่มเส้นทาง"}</h2><div className="form-grid"><label>รหัสเส้นทาง<input name="code" defaultValue={row?.code} readOnly={!!row} pattern="[A-Za-z0-9_-]+" required maxLength={64}/></label><label>ชื่อเส้นทาง<input name="name" defaultValue={r?.name} required maxLength={191}/></label><DateField name="from" label="เริ่มมีผล (พ.ศ.)" value={r?.effectiveFrom??data.serviceDate}/><DateField name="to" label="สิ้นสุด (พ.ศ.)" value={r?.effectiveTo??""} required={false}/></div><label className="check-label"><input name="active" type="checkbox" defaultChecked={row?.active??true}/>เปิดใช้งาน</label>
 <h3>จุดส่งตามลำดับ</h3>{stops.map((id,n)=><div className="stop-editor" key={n}><label>จุดส่งที่ {n+1}<select required value={id} onChange={e=>setStops(stops.map((s,k)=>k===n?e.target.value:s))}><option value="">เลือกจุดส่ง</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="planner-actions"><button data-editor-change type="button" disabled={!n} onClick={()=>{const s=[...stops];[s[n-1],s[n]]=[s[n],s[n-1]];setStops(s);}}>เลื่อนขึ้น</button><button data-editor-change type="button" disabled={n===stops.length-1} onClick={()=>{const s=[...stops];[s[n+1],s[n]]=[s[n],s[n+1]];setStops(s);}}>เลื่อนลง</button><button data-editor-change type="button" onClick={()=>setStops(stops.filter((_,k)=>n!==k))}>นำออก</button></div></div>)}<button data-editor-change type="button" onClick={()=>setStops([...stops,""])}>เพิ่มจุดส่ง</button><label>เหตุผล<input name="reason" required minLength={3} maxLength={500}/></label>{error&&<p role="alert">{error}</p>}<div className="planner-actions editor-save-bar"><button className="primary-button">บันทึกเส้นทาง</button><button className="secondary-button admin-back-button" type="button" onClick={close}><ArrowLeft size={18} aria-hidden="true"/>กลับรายการเส้นทาง</button></div></form>;
}
export function TemplateEditor({data,id,save,close}:{data:PlanningData;id?:string;save:Save;close:()=>void}){
 const row=data.templates.find(t=>t.id===id),r=row?.templateRevision_templateId[0],revisions=data.routes.flatMap(r=>r.routeRevision_routeId);const [routeId,setRouteId]=useState(r?.routeRevisionId??""),[cats,setCats]=useState(r?.templateStopCategory_templateRevisionId.map(c=>`${c.routeStopId}:${c.categoryId}`)??[]),[error,setError]=useState("");const route=revisions.find(r=>r.id===routeId);
 return <form className="admin-card admin-form" onSubmit={async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),minute=(name:string)=>minuteValue(field(f,name)),occupancy=(name:string)=>{const m=minute(name);return m===null?null:m+Number(f.get(`${name}Day`))*1440;};if(await save("template",{id:row?.id??newUuid(),code:field(f,"code"),expectedVersion:row?.version??0,active:f.get("active")==="on",effectiveFrom:isoDate(field(f,"from")),effectiveTo:field(f,"to")?isoDate(field(f,"to")):null,reason:field(f,"reason"),routeRevisionId:routeId,kind:field(f,"kind"),roundNo:Number(f.get("roundNo")),vehicleId:field(f,"vehicleId")||null,driverId:field(f,"driverId")||null,loadingMinute:minute("loadingMinute"),departureMinute:minute("departureMinute"),arrivalMinute:minute("arrivalMinute"),arrivalDayOffset:Number(f.get("arrivalDayOffset")),occupancyStartMinute:occupancy("occupancyStartMinute"),occupancyEndMinute:occupancy("occupancyEndMinute"),bufferMinutes:Number(f.get("bufferMinutes")),notes:field(f,"notes")||null,weekdays:f.getAll("weekday").map(Number),categories:route?.routeStop_routeRevisionId.map(s=>({routeStopId:s.id,categoryIds:data.categories.filter(c=>cats.includes(`${s.id}:${c.id}`)).map(c=>c.id)}))??[]}))close();}catch(e){setError(e instanceof Error?e.message:"ข้อมูลไม่ถูกต้อง");}}}>
 <h2>{row?"แก้ไขแม่แบบเป็นฉบับใหม่":"เพิ่มแม่แบบประจำ"}</h2><p className="muted">แม่แบบใหม่มีผลต่อเที่ยวที่ยังไม่ได้สร้าง เที่ยวเดิมและประวัติที่เผยแพร่จะคงฉบับอ้างอิงเดิม</p><div className="form-grid"><label>รหัสแม่แบบ<input name="code" defaultValue={row?.code} readOnly={!!row} required pattern="[A-Za-z0-9_-]+" maxLength={64}/></label><label>ฉบับเส้นทาง<select value={routeId} onChange={e=>{setRouteId(e.target.value);setCats([]);}} required><option value="">เลือกเส้นทาง</option>{data.routes.flatMap(route=>route.routeRevision_routeId.map(rev=><option value={rev.id} key={rev.id}>{route.code} — {rev.name} ฉบับ {rev.number}</option>))}</select></label><DateField name="from" label="เริ่มมีผล (พ.ศ.)" value={r?.effectiveFrom??data.serviceDate}/><DateField name="to" label="สิ้นสุด (พ.ศ.)" value={r?.effectiveTo??""} required={false}/><label>ประเภทเที่ยว<select name="kind" defaultValue={r?.kind??"BRANCH_DELIVERY"}>{Object.entries(kindLabels).filter(([k])=>k!=="OTHER").map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>รอบ<select name="roundNo" defaultValue={r?.roundNo??1}>{[1,2,3].map(n=><option key={n} value={n}>รอบ {n}</option>)}</select></label><label>รถ<select name="vehicleId" defaultValue={r?.vehicleId??""}><option value="">ยังไม่ระบุ</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.plateNormalized} {v.province}</option>)}</select></label><label>พนักงานขับรถ<select name="driverId" defaultValue={r?.driverId??""}><option value="">ยังไม่ระบุ</option>{data.drivers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 {([['loadingMinute','เริ่มขึ้นของ'],['departureMinute','ออกรถ'],['arrivalMinute','ถึงปลายทาง'],['occupancyStartMinute','เริ่มใช้รถ'],['occupancyEndMinute','สิ้นสุดใช้รถ']] as const).map(([key,label])=><label key={key}>{label}<TimeInput name={key} defaultValue={minuteText(r?.[key]??null)}/>{key.startsWith("occupancy")&&<span>จำนวนวันถัดไป<input name={`${key}Day`} aria-label={`${label} จำนวนวันถัดไป`} type="number" min={0} max={2} defaultValue={Math.floor((r?.[key]??0)/1440)}/></span>}</label>)}<label>ถึงปลายทางในวันถัดไป (จำนวนวัน)<input name="arrivalDayOffset" type="number" min={0} max={2} defaultValue={r?.arrivalDayOffset??0}/></label><label>เวลาเผื่อหลังใช้รถ (นาที)<input name="bufferMinutes" type="number" min={0} max={1440} defaultValue={r?.bufferMinutes??0}/></label><label>หมายเหตุ<textarea name="notes" maxLength={2000} defaultValue={r?.notes??""}/></label></div>
 <fieldset><legend>วันให้บริการ</legend><div className="planner-checks">{["จันทร์","อังคาร","พุธ","พฤหัสบดี","ศุกร์","เสาร์","อาทิตย์"].map((name,n)=><label key={n}><input name="weekday" value={n+1} type="checkbox" defaultChecked={r?.templateWeekday_templateRevisionId.some(w=>w.weekday===n+1)??true}/>{name}</label>)}</div></fieldset><h3>หมวดสินค้าประจำจุดส่ง</h3>{route?.routeStop_routeRevisionId.map(s=><fieldset key={s.id} className="stop-editor"><legend>{s.sequence}. {data.branches.find(b=>b.id===s.branchId)?.name}</legend><div className="planner-checks">{data.categories.map(c=><label key={c.id}><input type="checkbox" checked={cats.includes(`${s.id}:${c.id}`)} onChange={e=>setCats(e.target.checked?[...cats,`${s.id}:${c.id}`]:cats.filter(x=>x!==`${s.id}:${c.id}`))}/>{c.name}</label>)}</div></fieldset>)}<label className="check-label"><input name="active" type="checkbox" defaultChecked={row?.active??true}/>เปิดใช้งาน</label><label>เหตุผล<input name="reason" required minLength={3} maxLength={500}/></label>{error&&<p role="alert">{error}</p>}<div className="planner-actions editor-save-bar"><button className="primary-button">บันทึกแม่แบบ</button><button className="secondary-button admin-back-button" type="button" onClick={close}><ArrowLeft size={18} aria-hidden="true"/>กลับรายการแม่แบบ</button></div></form>;
}
